/**
 * Built-in resource types (pre-bundled).
 * Auto-generated by build.ts - DO NOT EDIT
 *
 * Resolver code receives ResolveContext (ctx) with:
 * - ctx.manifest: { domain, path?, name, type, version }
 * - ctx.files: Record<string, Uint8Array>
 *
 * Code format: ESM bundled code (without export statement)
 * The resolver variable name is stored in the code comment.
 */

import type { BundledType } from "./types.js";

/**
 * Plain text content
 */
export const textType: BundledType = {
  name: "text",
  aliases: ["txt", "plaintext"],
  description: "Plain text content",
  code: `// @resolver: text_type_default
// src/builtins/text.type.ts
var text_type_default = {
  name: "text",
  aliases: ["txt", "plaintext"],
  description: "Plain text content",
  async resolve(ctx) {
    const content = ctx.files["content"];
    return new TextDecoder().decode(content);
  }
};`,
};

/**
 * JSON content
 */
export const jsonType: BundledType = {
  name: "json",
  aliases: ["config", "manifest"],
  description: "JSON content",
  code: `// @resolver: json_type_default
// src/builtins/json.type.ts
var json_type_default = {
  name: "json",
  aliases: ["config", "manifest"],
  description: "JSON content",
  async resolve(ctx) {
    const content = ctx.files["content"];
    return JSON.parse(new TextDecoder().decode(content));
  }
};`,
};

/**
 * Binary content
 */
export const binaryType: BundledType = {
  name: "binary",
  aliases: ["bin", "blob", "raw"],
  description: "Binary content",
  code: `// @resolver: binary_type_default
// src/builtins/binary.type.ts
var binary_type_default = {
  name: "binary",
  aliases: ["bin", "blob", "raw"],
  description: "Binary content",
  async resolve(ctx) {
    return ctx.files["content"];
  }
};`,
};

/**
 * All built-in types as an array.
 */
export const builtinTypes: BundledType[] = [textType, jsonType, binaryType];
