/**
 * @resourcexjs/type - ResourceX Type System
 */

// Types
export type {
  ResourceType,
  ResourceResolver,
  ResolvedResource,
  ResolveContext,
  JSONSchema,
  JSONSchemaProperty,
  BundledType,
  IsolatorType,
} from "./types.js";

// Bundler
export { bundleResourceType } from "./bundler.js";

// Errors
export { ResourceTypeError } from "./errors.js";

// Type handler chain
export { TypeHandlerChain } from "./TypeHandlerChain.js";

// Builtin types (auto-generated by build.ts)
export { textType, jsonType, binaryType, builtinTypes } from "./builtinTypes.js";
