/**
 * ResourceX Registry HTTP API - Error Codes
 */

/**
 * Standard error codes
 */
export const ERROR_CODES = {
  // 400 Bad Request
  LOCATOR_REQUIRED: "LOCATOR_REQUIRED",
  MANIFEST_REQUIRED: "MANIFEST_REQUIRED",
  CONTENT_REQUIRED: "CONTENT_REQUIRED",
  INVALID_MANIFEST: "INVALID_MANIFEST",
  INVALID_LOCATOR: "INVALID_LOCATOR",
  INVALID_CONTENT: "INVALID_CONTENT",

  // 404 Not Found
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  CONTENT_NOT_FOUND: "CONTENT_NOT_FOUND",

  // 409 Conflict
  RESOURCE_EXISTS: "RESOURCE_EXISTS",
  VERSION_EXISTS: "VERSION_EXISTS",

  // 500 Internal Server Error
  INTERNAL_ERROR: "INTERNAL_ERROR",
  STORAGE_ERROR: "STORAGE_ERROR",
} as const;

/**
 * Error code type
 */
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * HTTP status codes for each error code
 */
export const ERROR_STATUS: Record<ErrorCode, number> = {
  // 400
  [ERROR_CODES.LOCATOR_REQUIRED]: 400,
  [ERROR_CODES.MANIFEST_REQUIRED]: 400,
  [ERROR_CODES.CONTENT_REQUIRED]: 400,
  [ERROR_CODES.INVALID_MANIFEST]: 400,
  [ERROR_CODES.INVALID_LOCATOR]: 400,
  [ERROR_CODES.INVALID_CONTENT]: 400,

  // 404
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 404,
  [ERROR_CODES.CONTENT_NOT_FOUND]: 404,

  // 409
  [ERROR_CODES.RESOURCE_EXISTS]: 409,
  [ERROR_CODES.VERSION_EXISTS]: 409,

  // 500
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.STORAGE_ERROR]: 500,
};

/**
 * Get HTTP status code for error code
 */
export function getStatusCode(code: ErrorCode): number {
  return ERROR_STATUS[code] ?? 500;
}
